name: User Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the service
        run: go build -v -o user-service .

      - name: Run tests
        run: go test -v ./...

      - name: Lint code
        run: golangci-lint run

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service:latest --push .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy user-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --port 50051 \
            --allow-unauthenticated
